WIP(instui-config,ui-navigation,ui-truncate-list): wip
instructure/instructure-ui pull request #1081
Opened 2022-08-05 15:26 UTC by ke1k0

2022-08-11 11:45 UTC, matyasf requested changes
Looks good except that the docs does not render the TS types 
<img width="643" alt="image" src="https://user-images.githubusercontent.com/2875286/184126212-0fc12cc3-0c74-4f83-bd60-97e19db86b00.png">

2022-08-11 11:45 UTC, matyasf commented on packages/ui-truncate-list/src/TruncateList/index.tsx
> +      ? []
could be a case where this is confusing to the users? I'd put it in the documentation that on the 1st render it can be empty

2022-08-12 11:22 UTC, HerrTopi approved these changes

2022-08-12 13:38 UTC, ke1k0 commented on packages/ui-truncate-list/src/TruncateList/README.md
> +The `onUpdate` function prop returns the number of visible items, and the `visibleItemsCount` prop controls how many items are currently visible. When not set, the list is not truncated.
Updated it! How about this:

```
The `onUpdate` function prop returns the number of visible items, and the `visibleItemsCount` prop controls how many items are currently visible.

It is a controlled component, so without and `onUpdate` prop it won't be responsive to changes. When `visibleItemsCount` is not set, the list is not truncated.
```

2022-08-12 13:39 UTC, ke1k0 commented
> Looks good except that the docs does not render the TS types <img alt="image" width="643" src="https://user-images.githubusercontent.com/2875286/184126212-0fc12cc3-0c74-4f83-bd60-97e19db86b00.png">

Nice catch, thanks! The @tsProps flag was missing. I added it to the component and the template component too.

2022-08-16 12:26 UTC, HerrTopi commented on packages/ui-truncate-list/src/TruncateList/README.md
> +The `onUpdate` function prop returns the number of visible items, and the `visibleItemsCount` prop controls how many items are currently visible. When not set, the list is not truncated.
It seems nice (:

2022-08-16 12:26 UTC, HerrTopi approved these changes

2022-08-17 11:49 UTC, merged