refactor: provide link to the Github theme variables
instructure/instructure-ui pull request #1102
Opened 2022-09-19 04:54 UTC by NamNguyenInstructure

Closes: INTUI-3548

2022-09-20 08:12 UTC, ke1k0 requested changes

2022-09-20 08:12 UTC, ke1k0 commented on packages/__docs__/src/Document/index.tsx
> +        You can check these variables at{' '}
Text suggestion: `See which global theme variables are mapped to the component here: [link]`

2022-09-20 08:12 UTC, ke1k0 commented on packages/__docs__/src/Document/index.tsx
> +        <Link href={legacySrcUrl || themeUrl}>{themePath}</Link>
I would also use this link in the block below on the "default theme variables" text.

<img width="1006" alt="Screenshot 2022-09-20 at 10 10 45" src="https://user-images.githubusercontent.com/11446033/191204053-adfab29b-d6a3-471a-9d8f-b15dabdfd9fb.png">

2022-09-30 13:31 UTC, matyasf approved these changes
nice!

2022-10-05 10:07 UTC, ke1k0 reviewed
Please merge the 2 commits into one (generally it is not nice to have "fix pr" commits littering the git history), and I think the commit type should be "docs" instead of "refactor".

2023-01-03 14:29 UTC, ke1k0 requested changes
Just had a small comment, otherwise looks good!

2023-01-03 14:29 UTC, ke1k0 commented on packages/__docs__/buildScripts/utils/getPathInfo.ts
> +  const ans: PackagePathData = {
I'd prefer more semantic names here, like `const: packagePathData: PackagePathData = { ... }`

2023-01-03 14:58 UTC, ke1k0 approved these changes

2023-01-03 15:39 UTC, merged