feat(ui-drilldown): allow controlled functionality when selecting options
instructure/instructure-ui pull request #1139
Opened 2022-12-21 18:41 UTC by Brailor

Closes: INSTUI-3685

users now are allowed to set a newly added `selected` property on `Drilldown.Option` which allows them to control the

selection logic from outside of the component fix `selectableType=single`allowing de-selecting options
TEST PLAN:
run the test cases, verify that
[this](https://codesandbox.io/s/flamboyant-glitter-2dt3bg?file=/index.js) use case is working as expected

2022-12-28 13:07 UTC, ke1k0 commented
I just tried the preview page, and the multi-select example throws an error when I try to navigate to a subpage: 
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/11446033/209816849-3d289168-da77-410f-8d12-ebf091cfe9a3.png">

Also, the single-select fix has to be a separate commit so that it shows up in the changelog.

2022-12-28 13:09 UTC, ke1k0 requested changes
I commented on the PR itself:
- the multi-select example throws error
- he single-select fix has to be a separate commit

2022-12-28 13:09 UTC, ke1k0 commented on packages/ui-drilldown/src/Drilldown/index.tsx
> +    // console.log({ optionProps })
not needed

2023-01-02 09:16 UTC, Brailor commented on packages/ui-drilldown/src/Drilldown/index.tsx
> +    // console.log({ optionProps })
Removed

2023-01-02 11:25 UTC, ke1k0 approved these changes
Seems good, thanks for separating the commits. I approved the PR, but if you have the time, it would be nice to add an example on the docs page to show this new controlled behaviour (or shall we try to keep it secret? XD)

2023-01-02 13:01 UTC, Brailor commented
> Seems good, thanks for separating the commits. I approved the PR, but if you have the time, it would be nice to add an example on the docs page to show this new controlled behaviour (or shall we try to keep it secret? XD)

For now I would keep it a "secret" until we are sure that this is working as expected.

2023-01-02 13:05 UTC, HerrTopi approved these changes

2023-01-02 13:06 UTC, merged