feat(instui-config,shared-types,ui-navigation,ui-side-nav-bar): add s…
instructure/instructure-ui pull request #1229
Opened 2023-07-07 08:22 UTC by HerrTopi

…ide-nav-bar component and deprecate navigation

Closes: INSTUI-3792

2023-07-12 10:04 UTC, matyasf requested changes
see my comments

2023-07-12 10:04 UTC, matyasf commented on packages/ui-side-nav-bar/CHANGELOG.md
> +**Note:** Version bump only for package @instructure/ui-side-nav-bar
I'd remove all the text from here since SideNavBar will start to exist in the next version

2023-07-12 10:04 UTC, matyasf commented on packages/ui-side-nav-bar/src/SideNavBar/__examples__/Navigation.examples.tsx
> +/*
This needs to be named SideNavBarExamples

2023-07-12 10:04 UTC, matyasf commented on packages/ui-side-nav-bar/src/SideNavBar/__tests__/Navigation.test.tsx
> +/*
This needs to be named SideNavBar.test.tsx

2023-07-12 11:35 UTC, balzss approved these changes
not related to the changes but the example is trying to call a non-existing function (`this.loadSubNav('account')`) which throws an error in the console

2023-07-17 10:04 UTC, matyasf approved these changes

2023-07-21 09:39 UTC, merged