WIP(ui-a11y-utils): don't close dialog on escape if file browser is open
instructure/instructure-ui pull request #1230
Opened 2023-07-12 11:18 UTC by balzss

Closes: INSTUI-3804

probably should wait until #1228 is merged

2023-07-17 10:09 UTC, matyasf approved these changes
nice work!

2023-07-17 10:15 UTC, matyasf requested changes
This change breaks the focus order, e.g. this code: (first Modal example)

```js
const fpo = lorem.paragraphs(5)

class Example extends React.Component {
  constructor (props) {
    super(props)

    this.state = {
      open: false
    }
  }

  handleButtonClick = () => {
    this.setState(function (state) {
      return { open: !state.open }
    })
  };

  handleFormSubmit = e => {
    e.preventDefault()
    console.log('form submitted')
    this.setState(state => ({ open: false }))
  }

  renderCloseButton () {
    return (
      <CloseButton
        placement="end"
        offset="small"
        onClick={this.handleButtonClick}
        screenReaderLabel="Close"
      />
    )
  }

  render () {
    return (
      <div style={{ padding: '0 0 11rem 0', margin: '0 auto' }}>
        <Button onClick={this.handleButtonClick}>
          {this.state.open ? 'Close' : 'Open'} the Modal
        </Button>
        <Modal
          as="form"
          open={this.state.open}
          onDismiss={() => { this.setState({ open: false }) }}
          onSubmit={this.handleFormSubmit}
          size="auto"
          label="Modal Dialog: Hello World"
          shouldCloseOnDocumentClick
        >
          <Modal.Header>
            {this.renderCloseButton()}
            <Heading>Hello World</Heading>
          </Modal.Header>
          <Modal.Body>
            <input type="file"/>
            <TextInput renderLabel="Example" placeholder="if you hit enter here, it should submit the form" />
            <Text lineHeight="double">{fpo}</Text>
          </Modal.Body>
          <Modal.Footer>
            <Button onClick={this.handleButtonClick} margin="0 x-small 0 0">Close</Button>
            <Button color="primary" type="submit">Submit</Button>
          </Modal.Footer>
        </Modal>
      </div>
    )
  }
}

render(<Example />)
```

If you try to tab trough the stuff in the Modal, it will lose focus when focusing on the file input.

2023-07-20 11:46 UTC, matyasf approved these changes

2023-07-20 13:44 UTC, HerrTopi approved these changes

2023-07-21 09:43 UTC, merged