Inst UI 3854 instui cli convert
instructure/instructure-ui pull request #1285
Opened 2023-09-13 14:12 UTC by joyenjoyer

### Test plan
Check all of the commands in the `instructure-ui/packages/instui-cli/README.md` if whether they work as they should.

2023-09-15 08:30 UTC, balzss requested changes
`package-lock.json` is not updated, run `npm install` and add it to this PR

2023-09-15 12:53 UTC, joyenjoyer commented
> `package-lock.json` is not updated, run `npm install` and add it to this PR

Done.

2023-09-15 12:58 UTC, joyenjoyer commented on packages/instui-cli/README.md
> +- **create-from-template** | Copy template source file or directory to a specified destination and replace variables with designated values.
We were having a discussion with Balazs about the `create-from-template` command here. Should this be deprecated as well?
@matyasf

2023-09-15 13:18 UTC, balzss approved these changes

2023-09-20 12:21 UTC, matyasf approved these changes
looks great!

2023-09-20 17:27 UTC, merged