feat(grid): add stretch option to vAlign
instructure/instructure-ui pull request #1293
Opened 2023-09-20 17:49 UTC by lalii05

My goal with this PR is to be able to stretch grid cells, so that if one cell is taller then the others then they can all get the same height.

2023-09-20 17:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/instructure/instructure-ui?pullRequest=1293) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/instructure/instructure-ui?pullRequest=1293) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/instructure/instructure-ui?pullRequest=1293) it.</sub>

2023-09-20 17:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/instructure/instructure-ui?pullRequest=1293) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/instructure/instructure-ui?pullRequest=1293) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/instructure/instructure-ui?pullRequest=1293) it.</sub>

2023-09-21 11:16 UTC, HerrTopi requested changes

2023-09-21 11:16 UTC, HerrTopi commented on packages/ui-grid/src/Grid/props.ts
> +  vAlign: PropTypes.oneOf(['top', 'middle', 'bottom', 'stretch']),
This stretch option needs to be added to the ts type above as well

2023-09-21 11:16 UTC, HerrTopi commented on packages/ui-grid/src/GridCol/props.ts
> +  vAlign: PropTypes.oneOf(['top', 'middle', 'bottom', 'stretch']),
This stretch option needs to be added to the ts type above as well

2023-09-21 11:16 UTC, HerrTopi commented on packages/ui-grid/src/GridRow/props.ts
> +  vAlign: PropTypes.oneOf(['top', 'middle', 'bottom', 'stretch']),
This stretch option needs to be added to the ts type above as well

2023-09-21 13:20 UTC, joyenjoyer approved these changes

2023-09-21 14:10 UTC, merged