feat(ui-date-time-input): make resetting programatically possible
instructure/instructure-ui pull request #1427
Opened 2024-02-02 14:51 UTC by HerrTopi

Closes: INSTUI-3982

2024-02-07 17:28 UTC, balzss requested changes
for me the docs example doesnt work:

- the `class` example doesn't allow me to select a data, only the time
- the `function` example doesn't reset when I press the Clear button

2024-03-05 10:18 UTC, matyasf approved these changes

2024-03-18 19:25 UTC, balzss approved these changes
looks and works great besides the minor typo

2024-03-18 19:25 UTC, balzss commented on packages/ui-date-time-input/src/DateTimeInput/props.ts
> +   * Te callback function will be called in componentDidMount
typo: `te` -> `the`

2024-03-21 09:23 UTC, merged