refactor(instui-cli,ui-codemods,ui-top-nav-bar): remove desktopConfig prop for v9
instructure/instructure-ui pull request #1464
Opened 2024-03-06 10:22 UTC by balzss

BREAKING CHANGE:
desktopConfig prop is removed from TopNavBar.Layout

2024-04-16 13:03 UTC, HerrTopi requested changes

2024-04-16 13:03 UTC, HerrTopi commented on packages/ui-react-utils/src/deprecated.ts
> +  if (process.env.NODE_ENV === 'pproduction') {
Probably not intentional :D Please fix this

2024-04-26 13:40 UTC, joyenjoyer commented on packages/ui-top-nav-bar/src/TopNavBar/TopNavBarLayout/DesktopLayout/index.tsx
> +  'further info: https://google.com'
I love using Google when I have a concern about something but is this really the best thing to recommend here?

2024-04-26 13:43 UTC, joyenjoyer requested changes
Please revisit the places I added a comment to.

2024-04-30 10:52 UTC, joyenjoyer approved these changes

2024-04-30 11:38 UTC, HerrTopi approved these changes

2024-04-30 15:24 UTC, merged