chore(release): 9.0.0
instructure/instructure-ui pull request #1509
Opened 2024-05-06 14:08 UTC by joyenjoyer

2024-05-06 14:38 UTC, matyasf requested changes
see my comments, other small stuff that needs to be changed:
- in the opening page of the docs it states '8.0 upgrade guide' and the whats new box links the 8,0 upgrade guide too
- https://1509--preview-instui.netlify.app/#usage adds InstUI `^8` as a dependency
-

2024-05-06 14:38 UTC, matyasf commented on docs/contributor-docs/v9-upgrade-guide.md
This is not a work in progress document (line 9)

2024-05-06 14:38 UTC, matyasf commented on docs/contributor-docs/v9-upgrade-guide.md
> +| [DateTime](#DateTime)                         | This util has been removed because it is not used by InstUI and other Instructure projects. If you need it, just copy & paste their code.
seems to be still here

2024-05-06 14:38 UTC, matyasf commented on docs/contributor-docs/v9-upgrade-guide.md
> +| Utility                                       | Substitute / Notes
We should not link the removed stuff, these just lead to 404 pages

2024-05-06 14:38 UTC, matyasf commented on docs/contributor-docs/v9-upgrade-guide.md
line 77: '...will be deleted in v9'. Isnt this v10? it would be good to list the exact changes here.

2024-05-07 11:18 UTC, HerrTopi approved these changes

2024-05-07 12:02 UTC, matyasf requested changes
Another issue: in CodeSandboxButton it will still pull in v8 dependencies:
```
'@instructure/debounce': '^8',
'@instructure/ui': '^8',
'@instructure/ui-icons': '^8',
```
when clicking on the "edit in CodeSandbox"

in docs/usage.md it still says "^8"

2024-05-09 09:15 UTC, git-nandor approved these changes

2024-05-09 10:31 UTC, merged