Inst UI 4066 investigation integration of vitest for unit testing
instructure/instructure-ui pull request #1516
Opened 2024-05-15 08:03 UTC by git-nandor

2024-05-31 13:12 UTC, balzss commented
looks great, I think we should go forward with this

2024-06-10 11:40 UTC, joyenjoyer commented on packages/ui-popover/src/Popover/__new-tests__/Popover.test.tsx
> +    //jest.resetAllMocks()
Consider removing this instead of commenting.

2024-06-14 11:30 UTC, balzss commented
I guess `jest` as a dependency could also be removed in this pr

2024-07-05 14:52 UTC, balzss requested changes
seems like vitest is running in watch mode by default (but not in CI), would be nice to disabled that

2024-07-05 14:53 UTC, balzss commented
also package-lock is not in synch with package.json, please update that

2024-07-09 08:28 UTC, matyasf requested changes
dev-commands.md needs to be around the "npm run test" part, it still says that the tests are running in Chrome. otherwise good job!

2024-07-09 12:01 UTC, balzss approved these changes
great job!

2024-07-10 11:26 UTC, matyasf approved these changes

2024-07-10 15:14 UTC, merged