fix(ui-tabs): fix horizontal scrolling with keyboard navigation
instructure/instructure-ui pull request #1521
Opened 2024-05-16 17:31 UTC by HerrTopi

2024-05-17 08:52 UTC, joyenjoyer approved these changes

2024-05-29 13:20 UTC, matyasf requested changes

2024-05-29 13:20 UTC, matyasf commented on packages/ui-tabs/src/Tabs/index.tsx
> +    setTimeout(() => {
This is very ugly :( 
If you put in such code please leave a detailed comment why this hack was necessary

2024-05-29 13:21 UTC, matyasf commented
Can you please add the JIRA ticket reference? Thanks!

2024-06-10 10:39 UTC, joyenjoyer approved these changes

2024-06-12 12:57 UTC, balzss approved these changes
works well

2024-06-13 11:40 UTC, merged