test(ui-pill): migrate old Pill tests
instructure/instructure-ui pull request #1565
Opened 2024-07-02 13:14 UTC by ToMESSKa

Closes: INSTUI-4112

2024-07-02 13:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/instructure/instructure-ui?pullRequest=1565) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/instructure/instructure-ui?pullRequest=1565) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/instructure/instructure-ui?pullRequest=1565) it.</sub>

2024-07-02 13:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/instructure/instructure-ui?pullRequest=1565) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/instructure/instructure-ui?pullRequest=1565) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/instructure/instructure-ui?pullRequest=1565) it.</sub>

2024-07-05 09:02 UTC, joyenjoyer commented on packages/ui-pill/src/Pill/__new-tests__/Pill.test.tsx
> +//test
please remove this line

2024-07-05 09:03 UTC, joyenjoyer requested changes
Remove the commented line.

2024-07-09 12:04 UTC, balzss approved these changes

2024-07-10 11:14 UTC, matyasf approved these changes

2024-07-10 13:29 UTC, joyenjoyer approved these changes

2024-07-16 09:27 UTC, merged