Inst UI 4119 convert UI link to the new test format
instructure/instructure-ui pull request #1577
Opened 2024-07-10 13:43 UTC by ToMESSKa

2024-07-10 13:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/instructure/instructure-ui?pullRequest=1577) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/instructure/instructure-ui?pullRequest=1577) before we can accept your contribution.<br/><hr/>**Tamas Kovacs** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/instructure/instructure-ui?pullRequest=1577) it.</sub>

2024-07-10 13:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/instructure/instructure-ui?pullRequest=1577) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/instructure/instructure-ui?pullRequest=1577) before we can accept your contribution.<br/><hr/>**Tamas Kovacs** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/instructure/instructure-ui?pullRequest=1577) it.</sub>

2024-07-15 09:17 UTC, balzss requested changes
jest should be replaced with vitest

2024-07-15 13:04 UTC, joyenjoyer approved these changes

2024-07-15 16:23 UTC, balzss approved these changes

2024-07-16 08:59 UTC, merged