feat(many): rewrite color system
instructure/instructure-ui pull request #1588
Opened 2024-07-17 21:48 UTC by HerrTopi

BREAKING CHANGE:
Breaks color overrides in certain cases

2024-07-18 08:35 UTC, balzss requested changes

2024-07-18 08:35 UTC, balzss commented on cypress/component/DateInput.cy.tsx
> +          'rgb(16, 135, 81)'
might be better to just delete this test

2024-07-18 08:35 UTC, balzss commented on cypress/component/Select.cy.tsx
> +        expect(iconStyles[1]).to.equal('rgb(17, 124, 186)')
and these two

2024-07-18 08:35 UTC, balzss commented on packages/__docs__/src/Theme/index.tsx
> +      // if (key === 'contrasts') {
why is this commented out? maybe delete it if we won't need it now or add a TODO comment if it's temporary

2024-07-18 09:59 UTC, git-nandor approved these changes

2024-07-18 12:51 UTC, matyasf requested changes

2024-07-18 12:51 UTC, matyasf commented on docs/guides/themes.md
> +- UI (colors)
add a bit explanation here too, e.g.

- Primitives: Base colors
- Contrasts: Theme building block, a color that takes up the value of a `primitive` based on the theme
- UI: Theme-specific color of a UI element like link text

2024-07-18 12:51 UTC, matyasf commented on docs/guides/themes.md
> +InstUI has a cross-theme (meaning they are the same for every theme) color palette, the `primitives`:
rewrite to something like: 
InstUI 's color palette is the same for every theme. The numbers in the color names denote the contrast ratio to XX

2024-07-18 12:51 UTC, matyasf commented on docs/guides/themes.md
> +Everythig is built using these colors. Ideally, our users should never interact directly with this palette, displayed only for reference.
Every theme in InstUI is built using these colors. Ideally users should never interact directly with this palette, here its only displayed only for reference.

2024-07-18 12:51 UTC, matyasf commented on docs/guides/themes.md
> +Contrasts are used internally by instUI and they are also the building blocks of the `UI` colors (see below). Ideally, our users should rarely or never interact directly with this abstraction, only i
typo: instUI-style

2024-07-18 12:51 UTC, matyasf commented on packages/emotion/src/__tests__/useTheme.test.tsx
> -    })
please do not delete these, here we are not testing for something that can be done by Chromatic, but the business logic of the theming engine

2024-07-18 12:51 UTC, matyasf commented on packages/emotion/src/__tests__/useTheme.test.tsx
> -  describe('with InstUISettingsProvider and global theme', () => {
please do not delete this, here we are not testing for something that can be done by Chromatic, but the business logic of the theming engine

2024-07-29 10:35 UTC, matyasf approved these changes
Great work! I've checked all components manually and they look OK and I could not find any bugs.

2024-07-31 14:43 UTC, merged