test(ui-metric): migrate old Metric tests
instructure/instructure-ui pull request #1617
Opened 2024-08-01 14:36 UTC by ToMESSKa

Closes: INSTUI-4150

2024-08-09 13:30 UTC, balzss approved these changes

2024-08-15 13:06 UTC, joyenjoyer commented on packages/ui-metric/src/Metric/__new-tests__/Metric.test.tsx
>    it('should allow methods and ReactNodes as labels and values', async () => {
I see that it accepts a div but what about methods? The test mentions that too. Please revisit this.

2024-08-15 13:07 UTC, joyenjoyer requested changes
Revisit this test please: `should allow methods and ReactNodes as labels and values`

2024-08-22 09:58 UTC, joyenjoyer approved these changes

2024-08-27 14:53 UTC, merged