feat(ui-calendar,ui-date-input): update DateInput2 api, add placeholder hint
instructure/instructure-ui pull request #1693
Opened 2024-09-23 09:54 UTC by balzss

v10 port of #1640

2024-09-26 12:03 UTC, matyasf requested changes
other than a new unit test would be good for `Calendar`, it looks good!

2024-09-27 16:22 UTC, balzss commented on packages/ui-calendar/src/Calendar/index.tsx
> +    )
is it ok if it's added to the separate pr with all the other unit tests for dateinput2?

2024-09-30 09:01 UTC, matyasf commented on packages/ui-calendar/src/Calendar/index.tsx
> +    )
yep, thats OK

2024-10-02 11:35 UTC, HerrTopi approved these changes

2024-10-02 11:36 UTC, merged