chore: rewrite deploy action to be able to deploy multiple versions to gh pages
instructure/instructure-ui pull request #1697
Opened 2024-09-24 13:15 UTC by joyenjoyer

2024-09-24 13:33 UTC, matyasf approved these changes

2024-09-24 14:41 UTC, HerrTopi approved these changes

2024-09-27 16:07 UTC, balzss commented
I guess this is outdated now and should be closed

2024-09-29 17:47 UTC, balzss requested changes
see #1702

2024-10-08 11:06 UTC, HerrTopi approved these changes
Seems good, needs testing tho. Good work

2024-10-08 11:48 UTC, matyasf approved these changes

2024-10-09 13:55 UTC, balzss approved these changes

2024-10-09 13:55 UTC, merged