chore: rewrite deploy action to be able to deploy multiple versions t…
instructure/instructure-ui pull request #1702
Opened 2024-09-27 14:40 UTC by joyenjoyer

…o gh pages

2024-09-27 16:14 UTC, balzss requested changes
please add some explanations to the code, otherwise nice work!

2024-09-27 16:14 UTC, balzss commented on .github/workflows/deploy.yml
> +            echo "::set-output name=build_dir::./packages/__docs__/__build__"
could this be set before the if/elif statement? it's the same for every condition

2024-09-27 16:14 UTC, balzss commented on packages/__docs__/_redirects_gh_pages
is this file needed? isn't it for netflity redirects?

2024-09-27 16:14 UTC, balzss commented on packages/__docs__/src/Header/index.tsx
> +    const rootToAdd = window.location.origin.includes('github.io')
please add and explanatory comment for this. could be a TODO with something like "remove when we permanently migrate to github.io"

2024-09-27 16:14 UTC, balzss commented on packages/__docs__/src/versionData.js
> +    let input = window.location.hostname.includes('github.io')
please add an explanation here too, maybe with a TODO remove later

2024-09-27 16:14 UTC, balzss commented on packages/__docs__/src/versionData.js
> +const versionInPath = /v\d$/.test(lastSegment) ? lastSegment : undefined
these 2 lines are not really straight forward. what do they do?

2024-10-10 14:14 UTC, HerrTopi approved these changes

2024-10-11 13:26 UTC, matyasf approved these changes

2024-10-11 14:51 UTC, balzss approved these changes

2024-10-11 14:52 UTC, merged