fix(ui-alert): trigger onDismiss for SR only alerts
instructure/instructure-ui pull request #1718
Opened 2024-10-08 15:11 UTC by csmaty

- `onDismiss` was not being fired on `screenReaderOnly` alerts, unless `transition: 'none'` was specified alongside.

- Default transition value is `'fade'`. This basically makes `screenReaderOnly` alerts an implicit `transition: 'none'`.

Credits for finding this bug: @meister245

2024-10-18 08:20 UTC, matyasf commented
it works great, thanks for the fix! Can you please squash the commits into one so there is just one with the `fix(ui-alerts): trigger onDismiss ...` commit message? Thanks!

2024-10-18 10:54 UTC, joyenjoyer requested changes
Great job, yes please squash the commits first.

2024-10-18 12:56 UTC, csmaty commented
@matyasf @joyenjoyer Squashed into a single commit.

2024-10-21 08:07 UTC, matyasf approved these changes
Thanks, we will merge and release it soon :)

2024-10-30 12:44 UTC, joyenjoyer approved these changes

2024-10-30 12:44 UTC, merged

2024-10-30 12:45 UTC, matyasf commented
Thanks for the contribution, we will release this soon!