chore: fix docs hot reload not working + convert webpack config to esm
instructure/instructure-ui pull request #1720
Opened 2024-10-09 12:37 UTC by balzss

INSTUI-4324

test plan:

- pull this pr, delete you node modules and run npm install + bootstrap
- run `npm run dev` and check if you update any source file, the dev server should reload
- check if you can find any file that doesn't trigger a reload when changed

2024-10-09 18:36 UTC, matyasf commented on package.json
> +    "@instructure/pkg-utils": "10.3.0",
These dont update automatically for some reason on `npm run bump`, can you please create a ticket for this?

2024-10-09 19:02 UTC, matyasf requested changes
regression test will fail because of package-lock.json changed

2024-10-10 11:59 UTC, matyasf approved these changes

2024-10-10 13:36 UTC, HerrTopi approved these changes

2024-10-10 13:37 UTC, merged