WIP(ui-checkbox,ui-form-field,ui-text-input): required asterisk and new form error messages
instructure/instructure-ui pull request #1729
Opened 2024-10-11 14:08 UTC by balzss

INSTUI-4321

2024-10-31 10:37 UTC, matyasf requested changes
Looks good as a WIP, just some things missing:
- description for some props
- I would make a page about forms in InstUI under Guides, where one can see all the components with some toggles that can set error, new error, required states.
- Please write unit tests too for these new props

2024-10-31 10:37 UTC, matyasf commented on packages/ui-checkbox/src/Checkbox/CheckboxFacade/props.ts
> +  error?: boolean
Please add some description about this new prop

2024-10-31 10:37 UTC, matyasf commented on packages/ui-checkbox/src/Checkbox/ToggleFacade/props.ts
> +  error: PropTypes.bool
here too

2024-10-31 13:34 UTC, ToMESSKa commented
in FileDrop, the error icon isn't aligned with the text the same way as in the rest of the components (it seems to be aligned to the bottom end vs to the top in the rest)

2024-10-31 13:36 UTC, ToMESSKa commented on packages/ui-file-drop/src/FileDrop/index.tsx
> +          return message.type === 'error' || message.type === 'newError'
in FileDrop, the error icon isn't aligned with the text the same way as in the rest of the components (it seems to be aligned to the bottom end vs to the top in the rest)

2024-10-31 13:47 UTC, ToMESSKa requested changes
In the second example on the CheckBoxGroup page, if the type is newError, the error message seems to be misplaced when layout='inline' (it appears in a separate column)

2024-11-06 10:20 UTC, matyasf approved these changes
Looks good, I really like the new 'form errors' page. Perhaps in the future we could expand it to a full documentation about forms in InstUI.

Also can you please write a VRT test for this (check out `TooltipPositioning.tsx`)

2024-11-06 11:21 UTC, ToMESSKa commented on packages/ui-radio-input/src/RadioInputGroup/props.ts
> +  /*
I think one more asterisk might be needed here e.g: /** because I cannot see this description on the preview page?

2024-11-06 16:16 UTC, ToMESSKa approved these changes

2024-11-06 16:59 UTC, merged