feat(ui-table): expand table api
instructure/instructure-ui pull request #1732
Opened 2024-10-11 19:13 UTC by HerrTopi

2024-10-12 14:17 UTC, balzss approved these changes

2024-10-14 09:42 UTC, matyasf requested changes
Please port the new Readme file too. I cant test there the new examples because the `TableContext` is not imported to the docs https://github.com/instructure/instructure-ui/pull/1652/files#diff-3b92b7bf7d9164bb15686f695dd0ab105f43548bc4aa5d2facd6e590057cddf3

2024-10-14 18:24 UTC, HerrTopi commented
> Please port the new Readme file too. I cant test there the new examples because the `TableContext` is not imported to the docs https://github.com/instructure/instructure-ui/pull/1652/files#diff-3b92b7bf7d9164bb15686f695dd0ab105f43548bc4aa5d2facd6e590057cddf3

Added.

2024-10-14 21:24 UTC, matyasf commented
hmm the custom examples are not working (e.g. hover state, functional code). I think its because TableContext is not exported from the main file https://github.com/instructure/instructure-ui/pull/1652/files#diff-22168e828cdc22d4d9e35b0c7626ec149648d8d366802f2b56b9b1f095691dc7

2024-10-15 12:34 UTC, matyasf approved these changes

2024-10-15 22:15 UTC, balzss approved these changes

2024-10-16 11:18 UTC, merged