feat(ui-view): borderColor prop added to ContextView, borderColor now…
instructure/instructure-ui pull request #1763
Opened 2024-11-07 10:41 UTC by ToMESSKa

… can be a HEX code in View

Closes: INSTUI-4346

2024-11-08 12:45 UTC, HerrTopi approved these changes
Nice work

2024-11-09 11:08 UTC, balzss requested changes
when using the old tokens for borderColor (`info`, `danger`, etc.) the small arrow always have black borders

2024-11-11 13:19 UTC, balzss commented
note: I've added a commit to remove the option from ContextView to support old color tokens (`info`, `danger`, etc.). You can still set them which would cause a mismatched border color but it is considered an invalid usecase.

2024-11-11 13:21 UTC, balzss approved these changes

2024-11-12 14:50 UTC, HerrTopi approved these changes

2024-11-13 14:14 UTC, merged