feat(ui-color-picker,ui-color-utils): add callback for contrast validation information and export validation methods
instructure/instructure-ui pull request #1768
Opened 2024-11-12 14:12 UTC by HerrTopi

Closes: INSTUI-4360

2024-11-13 13:02 UTC, matyasf requested changes
nice work, just some small documentation fixes from me

2024-11-14 14:17 UTC, HerrTopi commented on packages/ui-color-utils/src/overlayColors.ts
> +    a: 1
Done

2024-11-14 14:17 UTC, HerrTopi commented on packages/ui-color-utils/src/validateContrast.ts
> + *  for graphicsText, at least 3:1 contrast is required
Done

2024-11-14 14:17 UTC, HerrTopi commented on packages/ui-color-picker/src/ColorContrast/props.ts
> +   */
Done

2024-11-14 15:44 UTC, balzss approved these changes

2024-11-14 15:51 UTC, matyasf approved these changes

2024-11-14 15:51 UTC, merged