fix(ui-color-picker): make ColorPicker tooltip VoiceOver focusable
instructure/instructure-ui pull request #1771
Opened 2024-11-13 15:30 UTC by balzss

Closes: INSTUI-4259

test plan:

- check colorpicker example with tooltip if voiceover reads the tooltip context correctly

2024-11-13 16:00 UTC, ToMESSKa approved these changes

2024-11-13 17:09 UTC, matyasf requested changes
I dont like that the SR is focusing on nothing and the tooltip does not show with this solution.

I would solve the underlying issue, that icons set `aria-hidden` to `true` (in `InlineSVG`) by default. You just need a small change there to allow this attribute:

<img width="965" alt="image" src="https://github.com/user-attachments/assets/cb9f3071-9698-4211-9817-697759234346">

2024-11-22 21:24 UTC, balzss commented
@matyasf I've went with a different approach. According to [w3c](https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/) and [mdn](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role) tooltips should be focusable with keyboard.

2024-11-25 13:50 UTC, matyasf requested changes
I dont think this is a good solution. NVDA does not read the tooltip. Also its wonky on VO too, when I move the SR focus it does not read it, but after I've tabbed trough it, it will read it
I think its because the `svg` icon is set to `aria-hidden` which is a no for focusable elements https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden#description , so NVDA just removes is from the SR DOM

2024-11-28 11:40 UTC, balzss commented
@matyasf can you please check it again? now it also reads the tooltip when the input is focused but I don't think we can prevent that. I think it always reads the label when an input gets focused...

also fyi: it has a ts error that's probably introduced from [this pr](https://github.com/instructure/instructure-ui/pull/1771/files#diff-aacd5a00cfdc942924434e62ae19741c1a8d335477045d8cb9cdc143745454dfR397) so a [temporary ts-ignore](https://github.com/instructure/instructure-ui/pull/1771/files#diff-aacd5a00cfdc942924434e62ae19741c1a8d335477045d8cb9cdc143745454dfR397) was added

2024-11-29 10:03 UTC, matyasf commented on packages/ui-svg-images/src/InlineSVG/index.tsx
> -      children,
why did you remove this?

2024-11-29 10:03 UTC, matyasf approved these changes
nice work!

2024-11-29 10:05 UTC, matyasf commented on packages/ui-color-picker/src/ColorPicker/index.tsx
> +                componentOverrides: {
I did not knew that this is a valid syntax... easier one would be

```
  theme={{
    componentOverrides: {
      BaseButton: {
        smallHeight: 'auto'
      }
    }
  }}
```

2024-11-29 14:40 UTC, merged