feat(ui-breadcrumb,ui-tooltip): add tooltips for truncated breadcrumbs
instructure/instructure-ui pull request #1792
Opened 2024-11-26 14:51 UTC by HerrTopi

Closes: INSTUI-4371

2024-11-28 13:11 UTC, matyasf requested changes
see my comments. Sadly NVDA behaves very differently from VoiceOver

2024-11-28 13:11 UTC, matyasf commented on packages/ui-tooltip/src/Tooltip/props.ts
> +  preventTooltip?: boolean
can you please write a test for this?

2024-11-28 13:11 UTC, matyasf commented on packages/ui-breadcrumb/src/Breadcrumb/BreadcrumbLink/index.tsx
> +            <span aria-hidden={isTruncated}>{children}</span>
Saddly this is no good, NVDA ignores nodes that do not have text content or are set to `aria-hidden`. So here is just read 'button'

2024-11-29 10:41 UTC, matyasf commented on packages/ui-breadcrumb/src/Breadcrumb/BreadcrumbLink/index.tsx
> +          <TruncateText
wouldnt it be easier just to use here native text truncation?

2024-12-10 16:03 UTC, joyenjoyer commented
Let me know if you finish going through the requested changes and I will review it.

2025-03-26 15:29 UTC, matyasf approved these changes

2025-03-27 13:38 UTC, joyenjoyer approved these changes

2025-03-27 13:41 UTC, merged