WIP fix(ui-menu): screenreaders should read the correct number of menu items
instructure/instructure-ui pull request #1831
Opened 2024-12-18 14:44 UTC by matyasf

Closes: INSTUI-4285

Tested on VoiceOver, NVDA, JAWS. Also simplified DOM structure quite a bit, there are multiple examples of Menu online that do not use a List to wrap the whole thing, it was not needed

TEST PLAN:
Open the Menu example and go trough it with NVDA, JAWS, VoiceOver. You should be able to navigate and they should read the correct menu item number (e.g. 3 of 7).
Check the DOM structure with the inspector to see if it looks OK

2024-12-18 14:45 UTC, matyasf commented on packages/ui-menu/src/Menu/MenuItem/index.tsx
> -        return 'button'
A Menu having a `button` not a `menuitem` was driving NVDA crazy. NVDA really seems to be the most strict of them all

2024-12-18 14:46 UTC, matyasf commented on packages/ui-menu/src/Menu/MenuItemGroup/index.tsx
> -          aria-labelledby={this._labelId}
there is no need for `aria-labelledby` . Also its not usable for generic elements

2024-12-18 14:47 UTC, matyasf commented on packages/ui-menu/src/Menu/MenuItemGroup/index.tsx
> -          role="menu"
This should be used for submenus and menus, not for groups per specification https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menu_role

2025-02-03 11:14 UTC, balzss requested changes
left one comment but otherwise looks and works well, great job

2025-02-03 11:14 UTC, balzss commented on packages/ui-menu/src/Menu/index.tsx
>            this.props.controls
I can't add a comment to line 338 but I think the `<li>` wrapper around the menuseparator should be removed since you removed those elsewhere too and the `<ul>` parent so now that line doesn't make sense anymore

2025-02-03 12:45 UTC, matyasf commented on packages/ui-menu/src/Menu/index.tsx
>            this.props.controls
yea, you're right, I missed that one

2025-02-03 12:56 UTC, HerrTopi approved these changes

2025-02-03 13:01 UTC, balzss approved these changes

2025-02-03 13:07 UTC, merged