chore: add 'Skip to main content' button to the main page
instructure/instructure-ui pull request #1837
Opened 2024-12-20 09:12 UTC by ToMESSKa

Closes: INSTUI-4240

2025-01-06 12:32 UTC, matyasf requested changes
While it works good on the main page, it breaks on other pages. I think the good solution is to focus on the content container, it does not have to be an interactive element. 
This is done by e.g. wikipedia.com or github.com

2025-01-08 15:11 UTC, ToMESSKa commented
> While it works good on the main page, it breaks on other pages. I think the good solution is to focus on the content container, it does not have to be an interactive element. This is done by e.g. wikipedia.com or github.com

I fixed the above issues:
- now the focus should go to the container containing the main content
- the skip to Main button should also work the same way on the doc type pages (like Alert or API Guidelines) but was not implemented on the rest (like Icons or Changelog), I think it had no point to use this button on those pages

2025-01-09 09:16 UTC, matyasf requested changes
still not perfect, I could not trigger it when the side nav is open. Also AFAIK it should work for ALL pages, the main purpose of this feature is that if I send you a link like https://instructure.design/pr-preview/pr-1837/#CHANGELOG and you are a keyboard only SR user you dont have to tab trough our whole menu. Also its not nice to have a button that does nothing in this case. Cant you just move the focus to the content container?

2025-01-23 13:28 UTC, ToMESSKa commented
> still not perfect, I could not trigger it when the side nav is open. Also AFAIK it should work for ALL pages, the main purpose of this feature is that if I send you a link like https://instructure.design/pr-preview/pr-1837/#CHANGELOG and you are a keyboard only SR user you dont have to tab trough our whole menu. Also its not nice to have a button that does nothing in this case. Cant you just move the focus to the content container?

@matyasf I addressed this issue. Now the 'Skip to main button' should work on every page and also when the nav bar is open. Also added focus to Search bar inside of the navigation when open. Please check the revised test plan.

2025-01-24 15:51 UTC, matyasf approved these changes
nice work, works perfectly now :)

PS: The preview link is not up to date, I guess because of the merge conflict?

2025-01-28 08:54 UTC, ToMESSKa commented
> nice work, works perfectly now :)
> 
> PS: The preview link is not up to date, I guess because of the merge conflict?

@matyasf I resolved the merge conflict, the preview link seems up-to-date to me now.

2025-02-03 12:52 UTC, HerrTopi approved these changes

2025-02-03 13:06 UTC, merged