INSTUI-3314: deprecate navigation
instructure/instructure-ui pull request #825
Opened 2021-11-29 20:18 UTC by NamNguyenInstructure

2021-12-01 13:54 UTC, matyasf requested changes
besides the small text change it looks good

2021-12-01 13:54 UTC, matyasf commented on docs/guides/v8-deprecations.md
> +| [Navigation](#Navigation)               | This component has been deprecated from version 8.                                                                                                  |
I'd add here a bit more explanation:
This component is deprecated in v8 and will be removed in InstUI v9 due to the lack of usage.

2021-12-14 09:42 UTC, Brailor approved these changes

2021-12-14 11:51 UTC, matyasf approved these changes

2021-12-14 11:52 UTC, merged