chore(emotion,ui-i18n): throw warning when 'auto' dir (INSTUI-3306)
instructure/instructure-ui pull request #850
Opened 2021-12-14 13:54 UTC by HerrTopi

throw warning when 'auto' dir is passed to the TextDirectionContext

Closes: INSTUI-3306

2021-12-14 14:10 UTC, matyasf requested changes
BidirectionalProps still has a comment about 'auto' direction; ApplyTextDirectionProps still accepts 'auto'

2021-12-14 14:24 UTC, matyasf approved these changes

2021-12-14 14:53 UTC, ke1k0 requested changes
In the `ApplyTextDirection.test.tsx` it throws an error for the "auto" dir, please add a `ts-expect-error` that we intentionally pass it. It's also weird that this test passes, so we DO handle the auto value :)

2021-12-15 09:09 UTC, matyasf commented on packages/ui-i18n/src/ApplyTextDirection/__tests__/ApplyTextDirection.test.tsx
> -
if getTextDirection can return 'auto' we could move this test there

2021-12-15 15:12 UTC, ke1k0 approved these changes

2021-12-15 16:44 UTC, matyasf approved these changes
looks good, let's release

2021-12-15 16:52 UTC, merged